language: java

sudo: false

before_install: wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh

install:
  - . ./install-jdk.sh -F 10 -L BCL
  - chmod a+x ./gradlew
  - chmod a+x ./travis-build.sh

cache:
  directories:
    - $HOME/.gradle

script:
  - ./travis-build.sh
