language: java

sudo: false

before_install: wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh

install:
- . ./install-jdk.sh -F 11 -L BCL
- chmod a+x ./gradlew

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  target-branch: images
  local-dir: build/image-zip
  on:
    branch: master

cache:
  directories:
  - $HOME/.gradle

script: ./gradlew --info --stacktrace jlinkZip
